An example of BFS bottom-up approach using pykokkos
kokkos/pykokkos pull request #242
Opened 2024-01-12 07:02 UTC by Wilson1211

Given an n x m binary matrix, we want to return the distance of the nearest 0 for each cell as well as the distance farthest from cell 0. 
The distance between two adjacent cells is 1.
For example, given matrix:
0,0,0
0,1,0
1,1,1
we need to show that the distance of each cell to 0 is  
0,0,0
0,1,0
1,2,1
Also, the program will show the farthest distance to cell 0, in this example, the farthest distance to cell 0 is 2.

2024-01-12 14:28 UTC, gliga commented on examples/kokkos-tutorials/workload/bfs_bottomup.py
> +        self.Matrix: pk.View2D[pk.double] = pk.View([N, M], pk.double)
Matrix -> mat

2024-01-12 14:28 UTC, gliga commented on examples/kokkos-tutorials/workload/bfs_bottomup.py
> +
remove an extra empty line

2024-01-12 14:28 UTC, gliga commented on examples/kokkos-tutorials/workload/bfs_bottomup.py
> +
remove an extra empty line

2024-01-12 14:38 UTC, gliga commented on examples/kokkos-tutorials/workload/bfs_bottomup.py
> +        pk.parallel_for("02", self.N, self.findmax)
for the first argument in this call and calls below, you want to use/give unique names

2024-01-12 14:39 UTC, gliga commented on examples/kokkos-tutorials/workload/bfs_bottomup.py
> +        self.vis: pk.View1D[pk.double] = pk.View([N*M], pk.double)
is vis for visited? if yes, I would suggest expanding the name and using pk.int type

2024-01-12 14:40 UTC, gliga commented on examples/kokkos-tutorials/workload/bfs_bottomup.py
> +            if i>=self.M:
a comment for each branch would help follow code in this block

2024-01-12 14:41 UTC, gliga reviewed
mostly minor comments from my end.

I wish there was a way to provide an input from outside the workload and then we test it with various inputs, but this is fine for the first iteration

2024-01-12 20:53 UTC, NaderAlAwar reviewed
Looks good overall. I will take another look once the comments are addressed.

2024-01-12 20:53 UTC, NaderAlAwar commented on examples/kokkos-tutorials/workload/bfs_bottomup.py
> +            self.val[i] = N+M
Consider using the view `fill()` method to initialize views. You can apply this to all views in this class.

2024-01-12 20:53 UTC, NaderAlAwar commented on examples/kokkos-tutorials/workload/bfs_bottomup.py
> +        if (self.Matrix[var_row][var_col]==0) and (self.vis[i] == 0):
No need for parentheses here

2024-01-19 16:31 UTC, NaderAlAwar requested changes

2024-01-19 16:31 UTC, NaderAlAwar commented on examples/kokkos-tutorials/workload/bfs_bottomup.py
> +        self.max_arr2D: pk.View2D[pk.double] = pk.View([N, N], pk.double)
Try to follow the formatting in the other examples, no need for this many spaces

2024-01-19 16:31 UTC, NaderAlAwar commented on examples/kokkos-tutorials/workload/bfs_bottomup.py
> +        self.timer_result = timer.seconds()
At the moment, this timer isn't really timing anything. You can either remove it or move the call to `timer.seconds()`.

2024-01-19 16:33 UTC, NaderAlAwar commented
I would also move the location from `examples/kokkos-tutorials/workload` to `examples/graphs` (create a new directory)

2024-02-24 17:09 UTC, NaderAlAwar requested changes
The `parse_args.py` file is not needed here. You should instead use the `argparse` module directly in `bfs_bottump.py`, and you should only include the arguments you need, which are `M`, `N`, and `space` here

2024-03-10 18:15 UTC, NaderAlAwar approved these changes
Looks good, thanks!

2024-03-10 18:16 UTC, merged